Repository NOW-SOPT-APP6-BUBBLE/bubble-iOS, pull requests merged in 2024-05, with the labels that each got.

#3 [Chore] 깃허브와 프로젝트 파일 초기 세팅
  .github/ISSUE_TEMPLATE/🫧-bubble-ios-이슈-템플릿-🫧.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Bubble/Bubble.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Bubble/Bubble.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bubble/Bubble/.swiftlint.yml
  Bubble/Bubble/Application/AppDelegate.swift
  Bubble/Bubble/Application/Base.lproj/LaunchScreen.storyboard
  Bubble/Bubble/Application/Info.plist
  Bubble/Bubble/Application/SceneDelegate.swift
  Bubble/Bubble/Base/BaseCollectionViewCell.swift
  Bubble/Bubble/Base/BaseModel.swift
  Bubble/Bubble/Base/BaseTableViewCell.swift
  Bubble/Bubble/Base/BaseViewController.swift
  Bubble/Bubble/Extension/UIFont+.swift
  Bubble/Bubble/Extension/UIView+.swift
  Bubble/Bubble/Network/Common/MoyaLoggingPlugin.swift
  Bubble/Bubble/Network/Common/NetworkResult.swift
  Bubble/Bubble/Network/Common/Secret.swift
  Bubble/Bubble/Network/Model/TempModel.swift
  Bubble/Bubble/Network/Service/TempService.swift
  Bubble/Bubble/Network/TargetType/TempTargetType.swift
  Bubble/Bubble/Presentation/Home/HomeViewController.swift
  Bubble/Bubble/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Contents.json
  Bubble/Bubble/Util/Logger.swift
Labels: Chore ⚙️

#7 [Feat] 네비게이션 바 및 하단 탭바 구현
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble/Application/SceneDelegate.swift
  Bubble/Bubble/Extension/CALayer+.swift
  Bubble/Bubble/Extension/UIFont+.swift
  Bubble/Bubble/Presentation/Friends/FriendsViewController.swift
  Bubble/Bubble/Presentation/Home/HomeViewController.swift
  Bubble/Bubble/Presentation/TabBarController.swift
Labels: Feat 🫧

#10 [Feat] More 뷰 UI 구현
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bubble/Bubble/Enum/FontName.swift
  Bubble/Bubble/Enum/FontStyle.swift
  Bubble/Bubble/Extension/UIFont+.swift
  Bubble/Bubble/Extension/UILabel+.swift
  Bubble/Bubble/Network/Model/TempModel.swift
  Bubble/Bubble/Network/Service/TempService.swift
  Bubble/Bubble/Presentation/More/Cell/MoreTableVIewCell.swift
  Bubble/Bubble/Presentation/More/Model/MoreCellModel.swift
  Bubble/Bubble/Presentation/More/MoreViewController.swift
  Bubble/Bubble/Presentation/TabBarController.swift
Labels: Feat 🫧

#11 [Feat] 친구 목록 화면 UI 구현 완료
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bubble/Bubble/Base/BaseViewController.swift
  Bubble/Bubble/Enum/NavigationTitleName.swift
  Bubble/Bubble/Extension/NSObject+.swift
  Bubble/Bubble/Presentation/Friends/Cell/FriendsFooterView.swift
  Bubble/Bubble/Presentation/Friends/Cell/FriendsHeaderView.swift
  Bubble/Bubble/Presentation/Friends/Cell/FriendsTableViewCell.swift
  Bubble/Bubble/Presentation/Friends/FriendsViewController.swift
Labels: Feat 🫧

#19 [Chore] gitignore에 Secret 파일 추가 및 적용
  .gitignore
  Bubble/Bubble/Network/Common/Secret.swift
Labels: Chore ⚙️

#15 [Feat] 아티스트 상세 프로필 화면 구현 완료
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble/Extension/UIFont+.swift
  Bubble/Bubble/Extension/UILabel+.swift
  Bubble/Bubble/Presentation/Friends/FriendsViewController.swift
  Bubble/Bubble/Presentation/Friends/ProfileViewController.swift
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_artistChip.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_artistChip.imageset/icon_artistChip.svg
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_close_white.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_close_white.imageset/icon_close_white.svg
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_emptyStar.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_emptyStar.imageset/icon_emptyStar.svg
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_star.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_star.imageset/icon_star.svg
  Bubble/Bubble/Util/PaddingLabel.swift
Labels: Feat 🫧

#23 [Feat] Store 뷰 UI 구현
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bubble/Bubble/Enum/StoreStackViewHeight.swift
  Bubble/Bubble/Presentation/More/Cell/MoreTableVIewCell.swift
  Bubble/Bubble/Presentation/More/MoreViewController.swift
  Bubble/Bubble/Resource/Assets.xcassets/Artists/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist1.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist1.imageset/artist1.jpg
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist2.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist2.imageset/artist2.jpg
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist3.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist3.imageset/artist3.jpg
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist4.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist4.imageset/artist4.jpg
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist5.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Artists/artist5.imageset/artist5.jpg
  Bubble/Bubble/Resource/Assets.xcassets/Artists/storeHeaderImage.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Artists/storeHeaderImage.imageset/storeHeaderImage.png
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_rightArrow.imageset/Contents.json
  Bubble/Bubble/Resource/Assets.xcassets/Icons/icon_rightArrow.imageset/icon_rightArrow.svg
  Bubble/Bubble/Store/Cell/ArtistCollectionViewCell.swift
  Bubble/Bubble/Store/Model/StoreCellModel.swift
  Bubble/Bubble/Store/StoreViewController.swift
Labels: Feat 🫧

#25 [Feat] 아티스트 상세 프로필 조회 API 연동
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bubble/Bubble/Network/Service/ArtistMembersService.swift
  Bubble/Bubble/Network/TargetType/ArtistMembersTargetType.swift
  Bubble/Bubble/Presentation/Friends/FriendsViewController.swift
  Bubble/Bubble/Presentation/Friends/Model/ArtistProfileModel.swift
  Bubble/Bubble/Presentation/Friends/ProfileViewController.swift
Labels: Feat 🫧

#28 [Feat] 특정 아티스트 조회 API 연동
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble/Application/SceneDelegate.swift
  Bubble/Bubble/Network/Service/ArtistsServeice.swift
  Bubble/Bubble/Network/TargetType/ArtistsTargetType.swift
  Bubble/Bubble/Presentation/StoreDetail/Component/StoreDetailHeaderView.swift
  Bubble/Bubble/Presentation/StoreDetail/Component/StoreDetailInformationView.swift
  Bubble/Bubble/Presentation/StoreDetail/Component/StoreDetailPriceListView.swift
  Bubble/Bubble/Presentation/StoreDetail/Model/StoreDetailModel.swift
  Bubble/Bubble/Presentation/StoreDetail/Model/StoreDetailPrice.swift
  Bubble/Bubble/Presentation/StoreDetail/StoreDetailViewController.swift
  Bubble/Bubble/Util/CombineString.swift
  Bubble/Bubble/Util/WonFormatter.swift
Labels: Feat 🫧

#32 [Feat] 아티스트 즐겨찾기 삭제 API 연동
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble/Application/SceneDelegate.swift
  Bubble/Bubble/Network/Common/NetworkResult.swift
  Bubble/Bubble/Network/Service/ArtistMembersService.swift
  Bubble/Bubble/Network/Service/ArtistsServeice.swift
  Bubble/Bubble/Network/TargetType/ArtistMembersTargetType.swift
  Bubble/Bubble/Presentation/Friends/ProfileViewController.swift
Labels: Feat 🫧

#33 [Refactor] Store 뷰 수정
  Bubble/Bubble.xcodeproj/project.pbxproj
  Bubble/Bubble/Application/SceneDelegate.swift
  Bubble/Bubble/Enum/StoreCellHeight.swift
  Bubble/Bubble/Enum/StoreStackViewHeight.swift
  Bubble/Bubble/Network/Service/TermsCollectionViewCell.swift
  Bubble/Bubble/Presentation/More/Cell/MoreTableVIewCell.swift
  Bubble/Bubble/Presentation/More/MoreViewController.swift
  Bubble/Bubble/Presentation/Store/Cell/ArtistCollectionViewCell.swift
  Bubble/Bubble/Presentation/Store/Model/StoreCellModel.swift
  Bubble/Bubble/Presentation/Store/StoreViewController.swift
Labels: Refactor 🧺

#39 [Feat] 즐겨찾기 등록 API 연결, Store에서 DetailStore로 화면 연결
  Bubble/Bubble/Application/SceneDelegate.swift
  Bubble/Bubble/Network/Service/ArtistMembersService.swift
  Bubble/Bubble/Network/Service/ArtistsServeice.swift
  Bubble/Bubble/Network/TargetType/ArtistMembersTargetType.swift
  Bubble/Bubble/Network/TargetType/ArtistsTargetType.swift
  Bubble/Bubble/Presentation/Friends/ProfileViewController.swift
  Bubble/Bubble/Presentation/Store/StoreViewController.swift
  Bubble/Bubble/Presentation/StoreDetail/StoreDetailViewController.swift
Labels: Feat 🫧
